name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        uses: JRubics/gitlab-package-hunter@develop
        with:
          who-to-greet: 'Mona the Octocat'
